    services:
      postgres_hites_oltp:
        image: postgres:latest
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin1234
          POSTGRES_DB: hites_oltp_db
        volumes:
          - postgres-data:/var/lib/postgresql/data

    volumes:
      postgres-data: